[package]
name = "archer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
fs_extra = "1.3.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.22"
